name = "Batsrus"
uuid = "e74ebddf-6ac1-4047-a0e5-c32c99e57753"
version = "0.10.1"
authors = ["Hongyang Zhou <hyzhou@umich.edu>"]

[deps]
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
FHist = "68837c9b-b678-4cd5-9925-8a54edc8f695"
FortranFiles = "c58ffaec-ab22-586d-bfc5-781a99fd0b10"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NaturalNeighbours = "f16ad982-4edb-46b1-8125-78e5a8b5a9e6"
Parsers = "69de0a69-1ddd-5017-9359-2bf0b02dc9f0"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[weakdeps]
GaussianMixtures = "cc18c42c-b769-54ff-9e2a-b28141a64aae"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
WriteVTK = "64499a7a-5c06-52f2-abe2-ccb03c286192"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
LightXML = "9c8b4983-aa76-5018-a973-4c85ecc9e179"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"

[extensions]
BatsrusGaussianMixturesExt = "GaussianMixtures"
BatsrusMakieExt = "Makie"
BatsrusPyPlotExt = "PyPlot"
BatsrusWriteVTKExt = ["WriteVTK", "Glob", "LightXML"]
BatsrusHDF5Ext = "HDF5"

[compat]
DimensionalData = "0.29"
FHist = "0.11.17"
FortranFiles = "0.6"
GaussianMixtures = "0.3.13"
Glob = "1.3"
HDF5 = "0.17"
Interpolations = "0.14, 0.15, 0.16"
LightXML = "0.9"
LinearAlgebra = "1.10"
Makie = "0.21, 0.22, 0.23, 0.24"
NaturalNeighbours = "1.3"
Parsers = "2.4"
PrecompileTools = "1"
Printf = "1.10"
ProgressMeter = "1.10"
PyPlot = "2.9"
RecipesBase = "1.1"
Reexport = "1.2"
StaticArrays = "1.2"
Suppressor = "0.2.8"
Unitful = "1.7"
WriteVTK = "1.9"
julia = "1.10"

[extras]
GaussianMixtures = "cc18c42c-b769-54ff-9e2a-b28141a64aae"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
LazyArtifacts = "4af54fe1-eca0-43a8-85a7-787d91b784e3"
LightXML = "9c8b4983-aa76-5018-a973-4c85ecc9e179"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
WriteVTK = "64499a7a-5c06-52f2-abe2-ccb03c286192"

[targets]
test = ["CairoMakie", "GaussianMixtures", "Glob", "HDF5", "LazyArtifacts", "LightXML", "PyPlot", "SHA", "Suppressor", "Test", "WriteVTK"]
