name = "Batsrus"
uuid = "e74ebddf-6ac1-4047-a0e5-c32c99e57753"
authors = ["Hongyang Zhou <hyzhou@umich.edu>"]
version = "0.4.1"

[deps]
Dierckx = "39dd38d3-220a-591b-8e3c-4c3a8c710a94"
FortranFiles = "c58ffaec-ab22-586d-bfc5-781a99fd0b10"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
LightXML = "9c8b4983-aa76-5018-a973-4c85ecc9e179"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
WriteVTK = "64499a7a-5c06-52f2-abe2-ccb03c286192"

[weakdeps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[extensions]
BatsrusMakieExt = "Makie"

[compat]
Dierckx = "0.5"
FortranFiles = "0.6"
Glob = "1.3"
LightXML = "0.9"
Makie = "0.19, 0.20"
PyPlot = "2.9"
RecipesBase = "1.1"
Requires = "1.1"
Unitful = "1.7"
WriteVTK = "1.9"
julia = "1.6"